apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | quote }}
  labels:
{{- range $k, $v := .Values.namespace.labels }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"