{{- if .Values.resourcequota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ .Values.namespace.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: {{ .Values.resourcequota.hard.requestsCpu | quote }}
    requests.memory: {{ .Values.resourcequota.hard.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourcequota.hard.limitsCpu | quote }}
    limits.memory: {{ .Values.resourcequota.hard.limitsMemory | quote }}
    pods: {{ .Values.resourcequota.hard.pods | quote }}
    services: {{ .Values.resourcequota.hard.services | quote }}
    secrets: {{ .Values.resourcequota.hard.secrets | quote }}
    configmaps: {{ .Values.resourcequota.hard.configmaps | quote }}
{{- end }}
